app:
    resource: "@AppBundle/Controller/"

AppBundle_comments:
    resource: "@AppBundle/Resources/config/routing/comments.yml"
    prefix:   /comments   
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    
    

projects:
   path: /
   defaults: {_controller:AppBundle:Main:projects}
issues:
   path: /projects/{projectId}/issues
   defaults: {_controller:AppBundle:Main:issues}
issue:
   path: /issues/{issueId}
   defaults: {_controller:AppBundle:Main:showIssue}
track_time:
   path: /issues/{issueId}/time_entries/new
   defaults: {_controller:AppBundle:Main:trackTime}
logout:
   path: /logout
   

